[ui]
lang = "zh-CN"

[features]
push = true
annotate = true

[annotate.staged]
include_untracked = false

[annotate.form]
fields = ["reason", "reference_kind", "reference_value"]

[annotate]
reference_kinds = ["bug", "req"]

[annotate.render]
align_with_code_indent = false
wrap_blank_lines = true

[annotate.block_templates.add]
start = "// {author_tag} {date} add: {reason} ({reference_kind}:{reference_value})"
end = "// end add"

[annotate.block_templates.modify]
start = "// {author_tag} {date} modify: {reason} ({reference_kind}:{reference_value}) old={old}"
end = "// end modify"

[annotate.block_templates.del]
start = "// {author_tag} {date} del: {reason} ({reference_kind}:{reference_value}) old={old}"
end = "// end del"

[[annotate.file_rules]]
pattern = "*.c"
renderer = "c_line_block"

[[annotate.file_rules]]
pattern = "*.h"
renderer = "c_line_block"

[[annotate.file_rules]]
pattern = "*.cpp"
renderer = "c_line_block"

[[annotate.file_rules]]
pattern = "*.java"
renderer = "c_line_block"
